### ISSUE TITLE
unable to disable secret creation

### ISSUE THREAD

**Issue by switj** [zebrium/ze-kubernetes-collector#3]
Currently the chart always creates the secret and there is no way to disable it.

having a `secret.enabled` option would be very useful.

**Comment by zebrium** [comment]
Thanks for the suggestion. We can add that. However, I am curious why You have config before running “helm install” command. Did you create the secret manually?

**Comment by switj** [comment]
There are two workflows that this would enable. 

1. Using the chart to create the secret during the install then disable secret creation so further updates don't need the logging key. 
1.  create the secret during setup then use the chart to deploy everything else.

I created my own chart that has this chart as a requirement so that I'm able to override the values. I'm using `helm template --name <release-name> .` to generate the yaml then `kapp` to manage the deployment.

which would look something like this:
```
kapp deploy --app label:managed-by-kapp=${RELEASE_NAME}-${APP} \
  --namespace ${NAMESPACE} \
  --diff-changes --diff-context 4 \
  --wait=false --apply-default-update-strategy fallback-on-replace \
  --file <( helm template --name $RELEASE_NAME . )
```

**Comment by bradyzebrium** [comment]
Thanks, Josh. That makes sense. I have checked in a fix. Now you should be able to set "secret.enabled" to false to disable secret creation.

**Comment by switj** [comment]
changes look good, I'll try it out when the next release is out.
